
# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy a new task definition to Amazon ECS, when there is a push to the "dev" branch.
#
# To use this workflow, you will need to complete the following set-up steps:
#
# 1. Create an ECR repository to store your images.
#    For example: `aws ecr create-repository --repository-name my-ecr-repo --region us-east-1`.
#    Replace the value of the `ECR_REPOSITORY` environment variable in the workflow below with your repository's name.
#    Replace the value of the `AWS_REGION` environment variable in the workflow below with your repository's region.
#
# 2. Create an ECS task definition, an ECS cluster, and an ECS service.
#    For example, follow the Getting Started guide on the ECS console:
#      https://us-east-1.console.aws.amazon.com/ecs/home?region=us-east-1#/firstRun
#    Replace the value of the `ECS_SERVICE` environment variable in the workflow below with the name you set for the Amazon ECS service.
#    Replace the value of the `ECS_CLUSTER` environment variable in the workflow below with the name you set for the cluster.
#
# 3. Store your ECS task definition as a JSON file in your repository.
#    The format should follow the output of `aws ecs register-task-definition --generate-cli-skeleton`.
#    Replace the value of the `ECS_TASK_DEFINITION` environment variable in the workflow below with the path to the JSON file.
#    Replace the value of the `CONTAINER_NAME` environment variable in the workflow below with the name of the container
#    in the `containerDefinitions` section of the task definition.
#
# 4. Store an IAM user access key in GitHub Actions secrets named `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
#    See the documentation for each action used below for the recommended IAM policies for this IAM user,
#    and best practices on handling the access key credentials.
name: Build and Deploy to Amazon ECS
on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: weatherforecast         # seto this to your Amazon ECR repository name
  
permissions:
  contents: read
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
          registry-type: private
          
    - name: Build, tag, and push image to Amazon ECR Public
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        #REGISTRY_ALIAS: z8a4f8r0
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t weatherforecast .
        docker tag weatherforecast:latest 220379707701.dkr.ecr.us-east-1.amazonaws.com/weatherforecast:latest
        docker push 220379707701.dkr.ecr.us-east-1.amazonaws.com/weatherforecast:latest
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:latest"
        
  deploy:
      needs: build
      runs-on: [Linux]
      steps:
        - name: docker login ec2
          run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 220379707701.dkr.ecr.us-east-1.amazonaws.com
        - name: Run Docker clean
          run: docker ps -a -q
        - name: Run Docker Prune
          run: docker system prune -a --volumes -f
        - name: Run Docker restart
          run: sudo service docker restart
        - name: Pull Docker image from Amazon ECR
          run: docker pull 220379707701.dkr.ecr.us-east-1.amazonaws.com/weatherforecast:latest
        - name: Run Docker container
          run: docker run -d --name weatherforecast.${{ github.run_number }} -p 80:80 220379707701.dkr.ecr.us-east-1.amazonaws.com/weatherforecast
